### ISSUE TITLE
Separate the Zoom Links by Day of the Week

### ISSUE THREAD

**Issue by ninaahmed** [SamLab17/HelpHours#66]
We currently include the day of the week that a zoom link should be accessed on the link's label and we aren't visually separating the days. But visually separating the days could be helpful (and it was requested)! However, there are some classes that don't organize their zoom links by day.

If we wanted to combine separating the zoom links by day and our current format, we could do something like below. Words and sizing could be altered, of course.

<img width="1440" alt="Screen Shot 2021-01-08 at 2 42 31 AM" src="https://user-images.githubusercontent.com/41484890/103993405-2cc65000-515b-11eb-9d3d-ffea338b32a3.png">

I'm thinking we add a column to the zoomlinks table for the day of the week represented by an integer, something like 1-5 represents Monday-Friday and 0 is other. If there aren't any zoom links with a "day" value from 1-5, we won't display the calendar format at all.

The change zoom links window could have a format like the file linked below:
[sample_link_format.txt](https://github.com/SamLab17/HelpHours/files/5786098/sample_link_format.txt)

Or if that's too complicated for instructors we could always make a form type thing (select day, type description, paste link, enter; we can figure something out for deleting zoom links).

Thoughts ? Do we execute order 66 (see issue number)?

**Comment by SamLab17** [comment]
I think this is a good idea to implement and I really like the way you formatted it in the screenshot.

> If there aren't any zoom links with a "day" value from 1-5, we won't display the calendar format at all.

Good idea, and we could also get rid of the "Other Hours" heading in this case, since the "Other" would be a bit weird.

I think the form approach would be better. I already found the current solution with just a text field not very user-friendly and adding more to it like day of the week would make it worse. So maybe a form approach similar to the one we use for instructors could work nicely.

![palps](https://user-images.githubusercontent.com/24216390/104110224-2fc85a00-529b-11eb-9097-fbe227546e42.gif)

(I'd be happy to help with any part of this!)
