### ISSUE TITLE
Use JavaScript for Long Polling

### ISSUE THREAD

**Issue by SamLab17** [SamLab17/HelpHours#9]
## Description
Currently, we keep the user's view of the queue up to date by using long polling, achieved with a `meta` tag.

https://github.com/SamLab17/HelpHours/blob/f9966602fab70e7ccf025fa3839763ad125df25d/helphours/templates/view.html#L5-L11

@Andrew-William-Smith suspects this may be causing the rare Chrome pre-fetch issue and that using JavaScript could avoid this
"optimization" by Chrome.

## Open Questions:

Should we do this long polling if the queue is closed _and_ empty?

**Comment by Andrew-William-Smith** [comment]
> Should we do long polling if the queue is closed *and* empty?

We'll still have to long-poll regardless, as otherwise the user may not know when the line has opened or other people have joined.  I think that it's reasonable to decrease the polling frequency though: 300 seconds strikes me as a bit too long, but something like 15 seconds when open and 60 seconds when closed seems reasonable.  This increase in frequency will result in a larger number of requests, but given that the amount of data we'll be transferring will be substantially lower (i.e. just a JSON object instead of an entire webpage) we'll still be saving bandwidth.  We can set the rate limit to a little less than the maximum polling frequency (5 seconds or thereabouts) to ensure that no-one tries to DOS us and ship the initial line state via a Flask template when the user first loads the page.

**Comment by SamLab17** [comment]
I think the idea of passing around a JSON representation of the queue and rendering it on the front end is a good idea. It may also present some problems. 

I made an initial implementation [here](https://github.com/SamLab17/HelpHours/tree/js-long-polling). However, this does not support having buttons by the students' names when an instructor is logged in. I'm not sure how we should approach this. Before, adding those buttons when we rendered the template server-side was pretty straightforward:
https://github.com/SamLab17/HelpHours/blob/6e82d320617c5e7d03e44c470d82574ae47c707e/helphours/templates/view.html#L37-L44

I'm not too sure how/if we should do this on the front-end. Maybe we should have a different route to view the queue for instructors?

We may also need to edit this if we want to add a button for a student to remove themselves from the queue view.
